### PR TITLE
Fix issue 154 - language switcher failure

### LINKED ISSUE #154: Language switcher fails for not-logged-in users with 422
image

### PR DESCRIPTION
**Pull request by ktsubouchi**
This fixes #154 - 422 error when switching language preference.

Since preferences can be updated from multiple places and the controller method to update them required all preferences to be present in the POST request, 422 was returned when updating via the resource language preference switcher (only one preference sent).

Renamed the route and controller method and changed the route method to patch.  Updated the preference form and preference-related tests and tried to make the controller method more accommodating should additional preferences be required in the future.

Any feedback is welcome!

### CODE REVIEW

File: app/Http/Controllers/PreferenceController.php [hunk 1]
```diff
@@ -17,19 +17,15 @@ public function index()
...
-            'operating-system' => 'required',
-        ]);
+        $validKeys = $request->only(Preferences::getValidKeys());
 
-        Preferences::set([
-            'resource-language' => $request->input('resource-language'),
-            'locale' => $request->input('locale'),
-            'operating-system' => $request->input('operating-system'),
-        ]);
+        $filtered = array_filter($validKeys, function($val){
```
Comment (mattstauffer) [inline app/Http/Controllers/PreferenceController.php]: Would this work?

```php
Preferences::set($request->only(Preferences::getValidKeys())->filter());
```

This is relying on `filter()` to reject all null.. which i *think* it does?

Comment (ktsubouchi) [reply app/Http/Controllers/PreferenceController.php]: Wouldn't the only() have to be "collected" first and then converted back to an array? e.g.
```
Preferences::set(collect($request->only(Preferences::getValidKeys())->filter()->toArray());
```

I went with an explicit callback because I thought that there might potentially be valid preferences with values of 0 which would get filtered out without one.  Too much?

Comment (mattstauffer) [reply app/Http/Controllers/PreferenceController.php]: @ktsubouchi I'm OK if we go for the simpler version right now and have to refactor later if there's a valid `0`.

I'm bummed, I thought `only` came back with a collection.

```php
        Preferences::set(collect($request->only(Preferences::getValidKeys()))->filter());
```

This works, but it's definitely not the most readable thing *ever*.

Maybe this?

```php
        Preferences::set(
            collect($request->only(Preferences::getValidKeys()))->filter()
        );
```

If Preferences::set doesn't allow for a collection, I'd love to modify it so it does.

Comment (ktsubouchi) [reply app/Http/Controllers/PreferenceController.php]: Yeah, if `Preferences::set()` can accept a collection, that'll be cleanest.  I'll check into that.

Comment (ktsubouchi) [reply app/Http/Controllers/PreferenceController.php]: Made a mistake on the last push...I'll fix that.

Comment (ktsubouchi) [reply app/Http/Controllers/PreferenceController.php]: Okay, done.  Is that what you had in mind for the `Preferences::set()` method?

**Comment by mattstauffer** [comment]
Yesss! Thanks @ktsubouchi!
